### ISSUE TITLE
Login Menu not being prompted

### ISSUE THREAD

**Issue by gisone-bartolomeo-213704291** [EECS2311-Team8/SoftwareDevelopmentProject#126]
For latest version (release 2020-03-09-02-15-38). login page is not prompted when starting the application. Instead program immediately opens to the VennDiagram stage, and not the login page as described in the manual.

**Comment by gisone-bartolomeo-213704291** [comment]
More information:
on Windows 10, Java Version 8.0.2410.7

The expected result was for the login page to be prompted as described in the user manual.

simply opening the program will reproduce the bug.

**Comment by ReubenMathew** [comment]
Hi @gisone-bartolomeo-213704291, we are planning to update the manual with the removal of this feature until the team decides if we should implement this before our final sprint. For now this is considered a documentation issue and will be labelled as such.

Thanks for lettings us know!

**Comment by erick576** [comment]
Possibly added into future releases
