### ISSUE TITLE
Adding very long String Objects

### ISSUE THREAD

**Issue by gisone-bartolomeo-213704291** [EECS2311-Team8/SoftwareDevelopmentProject#127]
Adding an extremely long string and adding it will not only separate the Venn Diagram circles, but also make it impossible to click the undo, redo, clear all and export buttons. This breaks some of the program's main functions and thus will lead customers to close the application and lose previously made data.   

![VennFX bug1](https://user-images.githubusercontent.com/46453874/76688767-4a438f80-6606-11ea-8544-6caf624bdc67.PNG)

**Comment by gisone-bartolomeo-213704291** [comment]
More information:

Release 2020-03-09-02-15-38
on Windows 10, Java Version 8.0.2410.7

to replicate simply enter in an extremely long string of about 30+ characters.

The expected results were that the text-box would stop allowing character input after the string reaches a certain length .

**Comment by ReubenMathew** [comment]
Hi @gisone-bartolomeo-213704291 your issue is related to #116, keep up to date for progress on this bug by following that issue thread.

Thanks for pointing this out!

**Comment by erick576** [comment]
Fixed in latest Unreleased Version
