### ISSUE TITLE
Multiple of the same string

### ISSUE THREAD

**Issue by gisone-bartolomeo-213704291** [EECS2311-Team8/SoftwareDevelopmentProject#128]
Multiple instances of the same string can be populated to the Venn Diagram. Since this is a Venn Diagram, only one instance of a string should be used (i.e. there should be no copies and only unique strings).

To reproduce, simply rewrite the same String in the topmost text-box and enter in multiple of the same string.

Release 2020-03-09-02-15-38
on Windows 10, Java Version 8.0.2410.7

![VennFx bug2](https://user-images.githubusercontent.com/46453874/76688864-46643d00-6607-11ea-9807-10919532d235.PNG)

**Comment by erick576** [comment]
As requested from client any form of entry should be acceptable even duplicates
