### ISSUE TITLE
Long string

### ISSUE THREAD

**Issue by mah878** [EECS2311-Team8/SoftwareDevelopmentProject#129]
**Describe the bug**
Adding a long string could either make the element appear outside the Venn diagram or it appears in both sets. It also changes the circles sizes and if an extra long string is added the intersection disappears. 

**Expected behavior**
The user's element should stay in whichever set it chose. For example, if the user added an extra long string to set 1, the circle should increase its size for the circles so it does not appear outside of the circle or appear in any other circle as well. 

**Steps to Reproduce:**
 - Run VennFX.jar
 - Add a long string in the text box
 - Click "Enter"
 - The element is now added and shown in all sets and outside as well

**Screenshots**
![image](https://user-images.githubusercontent.com/46428304/76696503-96bcb880-6662-11ea-805d-aa9a2399e7c3.png)

**Desktop:**
 - OS: Windows 10
 - Release Tested:  Release-2020-03-09-02-15-38
 - Browser: Chrome
 - Java Version:  Java "1.8.0-231"
 - Report Type: Bug
 - Severity: Trivial
 - Priority: P1

**Comment by ReubenMathew** [comment]
Related to #127

**Comment by erick576** [comment]
Fixed in latest Unreleased Version
