### ISSUE TITLE
Elements outside the circle not removed

### ISSUE THREAD

**Issue by mah878** [EECS2311-Team8/SoftwareDevelopmentProject#130]
**Describe the bug**
Adding an element outside the circle should not be allowed. If an element is moved outside of its set, an option to delete the element should pop up.

**Expected behavior**
Element should be removed if taken outside of its circle, a window should pop with an option to ask the user if they are sure they want to remove this element since they are removing it from the circle. 

**Steps to Reproduce:**
 - Run VennFX.jar
 - Type in the text box and click "Enter"
 - Drag that element outside of its set
 - Element is not deleted completely 

**Screenshots**
![image](https://user-images.githubusercontent.com/46428304/76696727-ed2af680-6664-11ea-8052-a85c4c35c238.png)

**Desktop:**
 - OS: Windows 10
 - Release Tested:  Release-2020-03-09-02-15-38
 - Browser: Chrome
 - Java Version:  Java "1.8.0-231"
 - Report Type: Bug
 - Severity: Enhancement 
 - Priority: P2

**Comment by ReubenMathew** [comment]
Users might want to keep things outside of the circle to then later place them in the section of their choice.
