### ISSUE TITLE
Circle hovering over the color panel

### ISSUE THREAD

**Issue by mah878** [EECS2311-Team8/SoftwareDevelopmentProject#131]
**Describe the bug**
The circle's size increased and is now hovering over the circle 2 color panel, which makes it impossible to now change the color for that circle. 

**Expected behavior**
The circle's should not be close to any of the panels, so it does not affect the user when they increase the size of the circle. The user should not be forced to restart because of this error. 

**Steps to Reproduce:**
 - Run VennFX.jar
 - Add a element with a large string into any set
 - The circle's will now resize
 - The circle now hovers over the right panel
 - The right panel now crashes and cannot be used anymore
 - This forces the user to quit and restart their work

**Screenshots**
![image](https://user-images.githubusercontent.com/46428304/76696883-ca99dd00-6666-11ea-95b9-f38d5800f405.png)

**Desktop:**
 - OS: Windows 10
 - Release Tested:  Release-2020-03-09-02-15-38
 - Browser: Chrome
 - Java Version:  Java "1.8.0-231"
 - Report Type: Bug
 - Severity: Critical
 - Priority: P1

**Comment by erick576** [comment]
Close Issue Linked to #88
