### ISSUE TITLE
Unresizable window

### ISSUE THREAD

**Issue by sidharthsudarsan** [EECS2311-Team8/SoftwareDevelopmentProject#132]
##
**OS**: *macOS Mojave Version 10.14*
**Processor**: *2.5 GHz Intel Core i5*
**RAM**: *8GB*
**Priority**: *Immediate*
**Release**: *vM*
**Java Version**: *13.0.2*
##
## Description
The launch dimensions of the application exceeded the size of the screen. Resizing the window did not resize proportionately making some parts of the application inaccessible. In reference to the screenshots in the user manual, the *Clear All* and *Export* buttons were not accessible.

## Steps to Reproduce

1. Launch application
2. Resize window

##
![Screen Shot 2020-03-15 at 5 35 13 PM](https://user-images.githubusercontent.com/59708815/76711117-944e7300-66e3-11ea-97da-0c588aba34d2.png)

![Screen Shot 2020-03-15 at 5 31 26 PM](https://user-images.githubusercontent.com/59708815/76711118-96183680-66e3-11ea-8e7f-5c8b481920e9.png)
##

## Expected Result
A resized application window in its intended view that fits to my screen.

## Actual Result
Enlarged view of the application window that cannot be resized.

**Comment by erick576** [comment]
Close Issue linked to #88
