### ISSUE TITLE
No login screen

### ISSUE THREAD

**Issue by sidharthsudarsan** [EECS2311-Team8/SoftwareDevelopmentProject#133]
##
**OS**: *macOS Mojave Version 10.14*
**Processor**: *2.5 GHz Intel Core i5*
**RAM**: *8GB*
**Priority**: *Medium*
**Release**: *vM*
**Java Version**: *13.0.2*
##
## Description
The login screen as mentioned in the user manual is not displayed on launching the application. 

## Steps to Reproduce

1. Launch application

## Expected Result
A login system on launch is displayed where user can retrieve their old data.

## Actual Result
On launch, the interface for working with the venn diagram is displayed.

**Comment by erick576** [comment]
Will possibly be added in future releases
