### ISSUE TITLE
Text overlaps when added back to back

### ISSUE THREAD

**Issue by sidharthsudarsan** [EECS2311-Team8/SoftwareDevelopmentProject#134]
##
**OS**: *macOS Mojave Version 10.14*
**Processor**: *2.5 GHz Intel Core i5*
**RAM**: *8GB*
**Priority**: *High*
**Release**: *vM*
**Java Version**: *13.0.2*
##
## Description
While entering data on to the diagram from the text field on the top, if data is added in succession, the text that is populated onto the circle overlaps on the existing text that was populated at the same location, making them unreadable during creation.

## Steps to Reproduce

1. Enter text on the text field on the top.
2. Click *Enter*
3. Enter text on the text field on the top.
4. Click *Enter*

##
![Screen Shot 2020-03-15 at 5 51 17 PM](https://user-images.githubusercontent.com/59708815/76711374-d37dc380-66e5-11ea-9ac8-3b1ae94e1fd9.png)
##

## Expected Result
Text is populated one below the other or in any other organized way making it readable while dragging them to their appropriate positions.

## Actual Result
Text is populated on top of the previously added text.

**Comment by erick576** [comment]
Fixed in latest Unreleased Version
