### ISSUE TITLE
Bug/Issue 1 - Text Element can intersect between two Venn diagram circles

### ISSUE THREAD

**Issue by rajakumar-sharujan-216376410** [EECS2311-Team8/SoftwareDevelopmentProject#135]
**Product:** VennFX.jar

**Java Version:** 1.8

**Component:** Text creation and dragging onto the Venn diagram

**Platform:** PC

**OS:** Windows 10

**Severity of Bug:** Minor

**Priority:** P2

**Summary:** When the user inputs a text element into the Venn diagram, it can be placed in a position where it intersects between two sections of the Venn diagram. 

### Description
**Steps to Reproduce Bug:**
1. Run VennFX.jar
2. Write the following text: "Hi, this bug needs to be fixed" into the text field. It is located to the left beside the 'Add' button.
3. Click 'Add'
4. Drag the text element to the very right edge of the intersection side and drop it.

### Expected Result
The user is not allowed to drop a text element so that it intersects two or more sections of the Venn diagram.

### Actual Result
The user is able to drop a text element so that it intersects two or more sections of the Venn diagram.

### Screenshot
![VennFX](https://user-images.githubusercontent.com/46406888/76712492-f9a86100-66ef-11ea-9b40-a66bd47b223b.JPG)

### Build Date & Platform
March 15, 2020 and JavaFX via Eclipse

### Additional Builds and Platforms
N/A

**Resolution:** NEW

**Comment by erick576** [comment]
This situation will be specified in future documentation as to what side to expect the entry to be on in this situation. Will link it to #95
