### ISSUE TITLE
Bug/Issue 2 - The undo function does not work 

### ISSUE THREAD

**Issue by rajakumar-sharujan-216376410** [EECS2311-Team8/SoftwareDevelopmentProject#136]
**Product:** VennFX.jar

**Java Version:** 1.8

**Component:** Undo function

**Platform:** PC

**OS:** Windows 10

**Severity of Bug:** Minor

**Priority:** P2

**Summary:** The user cannot undo the changes that they have made.

### Description
**Steps to Reproduce Bug:**
1. Run VennFX.jar
2. Enter the text "hello" into the text field and click the 'Enter' button
3. Click on the 'Undo' button. (No changes occur, the text cannot be removed)

### Expected Result
The user should be able to undo the changes they have made onto the Venn diagram. 

### Actual Result
The user cannot undo the changes they have made onto the Venn diagram.

### Screenshot
![VennFX_Bug2](https://user-images.githubusercontent.com/46406888/76712847-9e2ba280-66f2-11ea-9be5-ff429987ffcb.JPG)

### Build Date & Platform
March 15, 2020 and JavaFX via Eclipse

### Additional Builds and Platforms
N/A

**Resolution:** NEW

**Comment by erick576** [comment]
Implemented in latest Unreleased Version
