### ISSUE TITLE
Bug/Issue 3 - Cannot change the text properties or attributes 

### ISSUE THREAD

**Issue by rajakumar-sharujan-216376410** [EECS2311-Team8/SoftwareDevelopmentProject#137]
**Product:** VennFX.jar

**Java Version:** 1.8

**Component:** Text properties or attributes

**Platform:** PC

**OS:** Windows 10

**Severity of Bug:** Enhancement 

**Priority:** P2

**Summary:** The user should be able to change the text properties or attributes according to their preference. This includes editing or changing the color, size and font of the text.

### Description
**Steps to Reproduce Bug:**
1. Run VennFX.jar
2. Enter the text "Hi, this bug needs to be fixed" into the text field and click on the 'Enter' button. 
3. Change the left container of the venn diagram to color 'black' and no need to change the right container (leave it set to default color 'white').
4. Drag the text "Hi, this bug needs to be fixed" onto the Venn diagram. 

### Expected Result
The user should be able to change the color, size and font of any text element to their preference. 

### Actual Result
The user cannot change the color, size and font of any text element to their preference. Hence, all text has default color set to 'black' and becomes hard to see under dark container colors. 

### Screenshot
![VennFX_Bug3](https://user-images.githubusercontent.com/46406888/76713364-88b87780-66f6-11ea-823c-f7f677615bbd.JPG)

### Build Date & Platform
March 15, 2020 and JavaFX via Eclipse

### Additional Builds and Platforms
N/A

**Resolution:** NEW

**Comment by erick576** [comment]
Will link it to current issue #123
