### ISSUE TITLE
Bug Report (Crash)

### ISSUE THREAD

**Issue by sanakhd** [EECS2311-Team8/SoftwareDevelopmentProject#138]
[Bug Report (Crash).pdf](https://github.com/EECS2311-Team8/SoftwareDevelopmentProject/files/4335524/Bug.Report.Crash.pdf)

**Comment by sanakhd** [comment]
**Product:** VennFX.jar
**Release Date: ** March 9th 2020
**Java Version:** 1.8
**Component:** Crash
**Platform:** ​Macbook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)

**Comment by erick576** [comment]
Should be a dependency Issue will link it to the next release #149
