### ISSUE TITLE
Bug Report (Enhancement)

### ISSUE THREAD

**Issue by sanakhd** [EECS2311-Team8/SoftwareDevelopmentProject#139]
[Bug Report (Enhancement).pdf](https://github.com/EECS2311-Team8/SoftwareDevelopmentProject/files/4335525/Bug.Report.Enhancement.pdf)

**Comment by sanakhd** [comment]
**Product:** VennFX.jar
**Release Date:**  March 9th 2020
**Java Version:** 1.8
**Component:** Crash
**Platform:** ​Macbook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
**Priority:** P2

**Comment by erick576** [comment]
Implemented in latest Unreleased Version
