### ISSUE TITLE
Bug Report (Overlapping)

### ISSUE THREAD

**Issue by sanakhd** [EECS2311-Team8/SoftwareDevelopmentProject#140]
[Bug Report (Overlapping).pdf](https://github.com/EECS2311-Team8/SoftwareDevelopmentProject/files/4335543/Bug.Report.Overlapping.pdf)

**Comment by sanakhd** [comment]
**Product:** VennFX.jar
**Release Date:**  March 9th 2020
**Java Version:** 1.8
**Component:** Crash
**Platform:** ​Macbook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
**Priority:** P1

**Comment by erick576** [comment]
Fixed in latest Unreleased Version
