### ISSUE TITLE
Long text causes overlapping issue

### ISSUE THREAD

**Issue by qureshey-tariq-216789166** [EECS2311-Team8/SoftwareDevelopmentProject#146]
Description:
When you input a text that is longer than one of the circles it overlaps to the next circle which makes it seem buggy.

To Reproduce:
1. Open .jar file
2. Add a string that is long
3. Press "Enter"
4. The text will now be overlapping to other circles

Expected behavior:
The circle should resize itself in order make it fit inside the intersection or the two outer circles.

Screenshots:
![image](https://user-images.githubusercontent.com/46577160/76720153-646a9400-6712-11ea-8538-e7efd86acf36.png)

Desktop:
 - OS: Windows 10
 - Release: Release-2020-03-09-02-15-38
 - Browser: Chrome
 - Java Version: 1.8.0-231
 - Priority: P1

**Comment by erick576** [comment]
Fixed in latest Unreleased Version
