### ISSUE TITLE
Undo/ Redo

### ISSUE THREAD

**Issue by qureshey-tariq-216789166** [EECS2311-Team8/SoftwareDevelopmentProject#147]
Description:
Undo/ Redo button is not functional at all.

To Reproduce:
1. Open the .jar file
2. Click on "Undo" or "Redo"
3. Error is the fact that it does not do anything

Expected behavior:
The Undo/ Redo button should function and Undo the action performed in the Venn Diagram application or Redo the last Undo performed.

Screenshots
![image](https://user-images.githubusercontent.com/46577160/76720642-bfe95180-6713-11ea-9e6a-9f5bc0ddd355.png)

Desktop:

 - OS: Windows 10
 - Release: Release-2020-03-09-02-15-38
 - Browser: Chrome
 - Java Version: 1.8.0-231
 - Priority: P1

**Comment by erick576** [comment]
Implemented in latest Unreleased Version
