### ISSUE TITLE
Panel Crashing

### ISSUE THREAD

**Issue by qureshey-tariq-216789166** [EECS2311-Team8/SoftwareDevelopmentProject#148]
Description:
When a text is long and the circles become extended, the entire panel crashes and everything becomes non functional

To Reproduce:
1. Open the .jar file
2. Input a text that is significantly long (longer than the actual input box)
3. Try to click on anything that would have been functional before Step 2
4. Observe the panel crashing and becoming non-functional 

Expected behavior
Even with the circles becoming apart, which is a bug on its own, the panel should function normally with the circle colour changing option.

Screenshots
![image](https://user-images.githubusercontent.com/46577160/76720952-ba403b80-6714-11ea-9248-f3ceb2b5cddd.png)

Desktop:

 - OS: Windows 10
 - Release: Release-2020-03-09-02-15-38
 - Browser: Chrome
 - Java Version: 1.8.0-231
 - Priority: P1

**Comment by erick576** [comment]
Bug resolved in Latest Unreleased Version
